### ISSUE TITLE
Pip install for coherence.

### ISSUE THREAD

**Issue by larryzhang95** [facuzeta/coherence#1]
I'm currently encountering an issue installing the coherence module created. 
![image](https://user-images.githubusercontent.com/29720526/39652520-aa8c34fe-4fa2-11e8-896b-6cd77a31bd45.png)

I'm currently receiving this stack trace, where you can observe the Value Error at the end. 
Wondering if I could resolve that from my own machine, or if the code-base can handle this discrepancy. 
I've run this in both python2.7 and 3.5.

**Comment by facuzeta** [comment]
I nerver tried to install this on a windows so.
The problem is: it could not store the trained model because it cant create the path or something like that. Try to edit your code and change the path where it is looking for the model.
